spring:
  #rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  #mail
  mail:
    host: smtp.163.com
    username: suocaiyuan@163.com
    password: 123
    from: suocaiyuan@163.com
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

